### ISSUE TITLE
Cannot run binary even when nix-ld is installed.

### ISSUE THREAD

**Issue by WiredMic** [nix-community/nix-ld#85]
I am trying to use Platformio. How ever it uses unpatched  binaries when compiling code. 
I then setup a develop environment using flakes and nix-ld.
```nix
{
  description = "A basic flake with a shell";
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.05";
  inputs.flake-utils.url = "github:numtide/flake-utils";
  inputs.nix-ld.url = "github:Mic92/nix-ld";
  # this line assume that you also have nixpkgs as an input
  inputs.nix-ld.inputs.nixpkgs.follows = "nixpkgs";

  outputs = { nixpkgs, flake-utils, nix-ld, ... }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        # buildInputs = with pkgs; [  ];
      in with pkgs; {
        programs.nix-ld.enable = true;
        devShells.default = mkShell {
          packages = with pkgs; [ gcc zlib stdenv.cc.cc.lib platformio-core ];
          NIX_LD_LIBRARY_PATH =
            lib.makeLibraryPath [ pkgs.stdenv.cc.cc.lib openssl gcc ];
          NIX_LD = lib.fileContents "${stdenv.cc}/nix-support/dynamic-linker";
          # inherit buildInputs;

          shellHook = ''
            export LD_LIBRARY_PATH=$NIX_LD_LIBRARY_PATH
            export PLATFORMIO_CORE_DIR=$(pwd)/.platformio
            echo Hi
          '';
        };
      });
}
```
I then enter the shell by running `nix develop --impure -c $SHELL`.

When I look at the binary with `ldd` I get the output
```shell
ldd .platformio/packages/toolchain-xtensa-esp32s3/bin/xtensa-esp32s3-elf-g++
	linux-vdso.so.1 (0x00007ffff7fc6000)
	libstdc++.so.6 => /nix/store/qksd2mz9f5iasbsh398akdb58fx9kx6d-gcc-13.2.0-lib/lib/libstdc++.so.6 (0x00007ffff7c00000)
	libm.so.6 => /nix/store/r8qsxm85rlxzdac7988psm7gimg4dl3q-glibc-2.39-52/lib/libm.so.6 (0x00007ffff7edd000)
	libc.so.6 => /nix/store/r8qsxm85rlxzdac7988psm7gimg4dl3q-glibc-2.39-52/lib/libc.so.6 (0x00007ffff7a13000)
	/lib64/ld-linux-x86-64.so.2 => /nix/store/r8qsxm85rlxzdac7988psm7gimg4dl3q-glibc-2.39-52/lib64/ld-linux-x86-64.so.2 (0x00007ffff7fc8000)
	libgcc_s.so.1 => /nix/store/qksd2mz9f5iasbsh398akdb58fx9kx6d-gcc-13.2.0-lib/lib/libgcc_s.so.1 (0x00007ffff7eb8000)
```
I think this means that it has all dependents.  
However, when I try to run the binary I still get the generic NixOS error message:
```shell
Could not start dynamically linked executable: .platformio/packages/toolchain-xtensa-esp32s3/bin/xtensa-esp32s3-elf-g++
NixOS cannot run dynamically linked executables intended for generic
linux environments out of the box. For more information, see:
https://nix.dev/permalink/stub-ld
```
How do I activate nix-ld so I can run this binary?

**Comment by SuperSandro2000** [comment]
That's not how nixos modules work.
You must enable this on your host.

**Comment by Mic92** [comment]
Have something like this in your nixos configuration: https://github.com/Mic92/dotfiles/blob/main/nixos/modules/nix-ld.nix
Just now you are only configuring nix-shell, but not the OS part.

**Comment by WiredMic** [comment]
I have now actived nix-ld on my host machine and added all of the packages Mic92 has in his config. However I still get the error message:
```shell
❯ .platformio/packages/toolchain-xtensa-esp32s3/bin/xtensa-esp32s3-elf-g++
Could not start dynamically linked executable: .platformio/packages/toolchain-xtensa-esp32s3/bin/xtensa-esp32s3-elf-g++
NixOS cannot run dynamically linked executables intended for generic
linux environments out of the box. For more information, see:
https://nix.dev/permalink/stub-ld
```

**Comment by Mic92** [comment]
If you set up nix-ld correctly you see a symlink to nix-ld like this:

% ls -la /lib64/ld-linux-x86-64.so.2
lrwxrwxrwx root root 65 B a week ago  /lib64/ld-linux-x86-64.so.2@ ⇒ /nix/store/cn6w4x9ng7mklakmcf5i6jfishz0g6l1-nix-ld/libexec/nix-ld

If not, you either haven't enabled nix-ld or your nixos configuration didn't got applied correctly. The error messages you are seeing is coming from the default stub-ld.

**Comment by WiredMic** [comment]
Thank you. It work when I disabled stub-ld
```nix
environment.stub-ld.enable = false;
```

**Comment by zaldnoay** [comment]
> Thank you. It work when I disabled stub-ld
> 
> ```nix
> environment.stub-ld.enable = false;
> ```

This should be related to stub-ld module in upstream nixpkgs/nixos, check this commit https://github.com/NixOS/nixpkgs/commit/0863f6d2da0be5e8d7e3fb316ef58cdfe145220b.

Also, an ldso module has been added upstream to provide the ability to customize the ldso path https://github.com/NixOS/nixpkgs/commit/bf6f0d3cf4e1ed8c146b4e028b80be26383f5036. I think we can change the tmpfiles.d link to use the ldso module.
