### ISSUE TITLE
Does nix-ld work with steam?

### ISSUE THREAD

**Issue by Redhawk18** [nix-community/nix-ld#94]
Hey I was having issues with a game that uses the love2d engine, After some debugging with the dev team then the engine team I found the reason the game fails to launch on steam was it was missing libfuse. So I added fuse to my nix-ld list of libs and relaunched steam and I got the same error.

**Comment by SuperSandro2000** [comment]
I could imagine that steam is providing its own ld in the Linux runtime.

Btw are you using that? If not, try using it, it should make things work better generally.

**Comment by Redhawk18** [comment]
> I could imagine that steam is providing its own ld in the Linux runtime.
> 
> Btw are you using that? If not, try using it, it should make things work better generally.

What do you mean? [Also on discord I asked and NobbZ responded that it won't work because steam runs in a FHSenv.](https://discord.com/channels/568306982717751326/860017489311694848/1297672257249742870)

**Comment by Mic92** [comment]
steam-run will shadow nix-ld with it's own mount sandbox. This is not a limitation of nix-ld, but a design aspect of steam-run. If you need more libraries, they should go into steam-run instead. Both approaches are orthogonal.

**Comment by Mic92** [comment]
Looks like you can add extra libraries through an override: https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/st/steam/package.nix#L7
